### ISSUE TITLE
`apt update` fails with HTTP code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by mpsijm** [gyazo/Gyazo-for-Linux#108]
Title says it all, I included the console output for the `apt update` command below.
When I wait a day between running `apt update` again, I get the same error.
I also tried re-installing, without success.

```
# apt update
Hit:1 http://nl.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://nl.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB] 
(...)
Ign:21 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu xenial InRelease
Err:22 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu xenial Release
  429  Too Many Requests
Reading package lists... Done 
E: The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by pastak** [comment]
Oh, sorry we reach bandwidth limit on packagecloud.io .  We will update packagecloud account. Please wait for a while 🙇

**Comment by pastak** [comment]
We have updated packagecloud account plan. Please retry it.

**Comment by mpsijm** [comment]
Thanks for resolving the issue, it works again :smile: :tada:

**Comment by purandarbarman** [comment]
Facing this issue again. Bandwidth limit has been reached.
Can someone look into it or tell me where can I post this.
