### ISSUE TITLE
cant install gyazo

### ISSUE THREAD

**Issue by ashee69** [gyazo/Gyazo-for-Linux#11]
i encountered with this error, can anyone help ?
GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_5ftransaction_5ferror.Code4: SimulateInstallFiles not supported by backend

**Comment by Gloomshroud** [comment]
I fixed my problem by using a distro closer to "stock" Ubuntu (Xubuntu 14.04). I was able to get Gyazo up and running with no issues whatsoever on a more "mainstream" line. So my problem has been resolved completely, in a manner of speaking. Using Gyazo hassle-free now! Keep up the excellent work folks!
