### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Vringe** [gyazo/Gyazo-for-Linux#112]
Successfully installed gyazo on Fedora 27 with `dnf install gyazo`.
How can I upload screenshots directly into my account? (Pro)

Currently, I have to press "Save Image" each time.

**Comment by pastak** [comment]
Which version you use? We have fixed v1.3.1 same issue. Please notice more info if it won't work

**Comment by Vringe** [comment]
Oh, I had v1.2.3
I reinstalled it over packagecloud, which seems now to work. Thank you!
