### ISSUE TITLE
Kubuntu 17.10 - where is the app? It's missed from the menu

### ISSUE THREAD

**Issue by OnkelTem** [gyazo/Gyazo-for-Linux#113]
subj + and I have no ideas how to run it.

**Comment by nna774** [comment]
If you installed collectly, gyazo cmd is located at `/usr/bin/gyazo`.
Can you run from terminal by typing `gyazo` (or `/usr/bin/gyazo`)?
If you can, you can add an app from KDE settings(like [this?](https://userbase.kde.org/Plasma/HowTo/4.5) I've never used KDE, so I don't know in detail).

**Comment by OnkelTem** [comment]
No, it's not there. Hm...

**Comment by OnkelTem** [comment]
Ok, I don't know what went wrong, now I could install it and it seems running.
Thank you.
