### ISSUE TITLE
Error Ubuntu 16.04 when taking screenshots

### ISSUE THREAD

**Issue by tranthaihoang** [gyazo/Gyazo-for-Linux#114]
I am constantly experiencing the selection frame when taking screenshots, this is the picture when finished
https://gyazo.com/2a6c3bc9a5e31e8a40deb81d5c731a03

**Comment by pastak** [comment]
You should use `gnome-screenshot` instead of default `import` command.

See: https://github.com/gyazo/Gyazo-for-Linux#change-your-screenshot-commandtool
