### ISSUE TITLE
gyazo for elementary os

### ISSUE THREAD

**Issue by Htou** [gyazo/Gyazo-for-Linux#115]
is it possible to install this on elementary os? And how do I do that?

**Comment by pastak** [comment]
@squirtpower You can install to elementary os by using `apt-get` like here: https://github.com/gyazo/Gyazo-for-Linux#apt-get-install

**Comment by squirtpower** [comment]
I tried that but it did not work for me. Terminal gives me this problem
![screenshot from 2018-04-13 20 12 06](https://user-images.githubusercontent.com/25567913/38751043-25160f4e-3f57-11e8-8bbc-ba617df82b53.png)

 I have no idea on how to overwrite the distro.

**Comment by pastak** [comment]
@squirtpower I pushed package for `elementaryos/loki`. Please retry it 🙏

**Comment by squirtpower** [comment]
@pastak I tried again but I get the same window. IS there another way to install this?

**Comment by pastak** [comment]
@squirtpower ummm... How does works `curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo os=ubuntu dist=xenial bash`?

**Comment by Htou** [comment]
<a href="https://gyazo.com/1eac0183c1312a261a28c1e1e6376dd4"><img src="https://i.gyazo.com/1eac0183c1312a261a28c1e1e6376dd4.png" alt="https://gyazo.com/1eac0183c1312a261a28c1e1e6376dd4" width="1504"/></a>

it worked thanks alot!
