### ISSUE TITLE
Not supported by zorin os

### ISSUE THREAD

**Issue by fluid3** [gyazo/Gyazo-for-Linux#120]
zorin os should be available for ubuntu derivation, but it can not be installed.

> Detected operating system as Zorin/xenial.
> Checking for curl...
> Detected curl...
> Checking for gpg...
> Detected gpg...
> Running apt-get update... done.
> Installing apt-transport-https... done.
> Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...curl: (22) The requested URL returned error: 404 Not Found
> 
> 
> Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=Zorin&dist=xenial&source=script
> 
> This usually happens if your operating system is not supported by 
> packagecloud.io, or this script's OS detection failed.
> 
> You can override the OS detection by setting os= and dist= prior to running this script.
> You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version
> 
> For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh
> 
> If you are running a supported OS, please email support@packagecloud.io and report this.

**Comment by pastak** [comment]
Please try https://github.com/gyazo/Gyazo-for-Linux/issues/35#issuecomment-386000518

**Comment by fluid3** [comment]
Thanks!
