### ISSUE TITLE
Public Key is Not Available

### ISSUE THREAD

**Issue by sangoku116** [gyazo/Gyazo-for-Linux#126]
I am on Zorin OS 12.4 and getting this error when I try to update:

`Get:13 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease [23.6 kB]
Err:13 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
Fetched 130 kB in 1s (89.6 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
W: Failed to fetch https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu/dists/trusty/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

Here is what I get when I try to request the key from the server:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9D0A7D764367AC46
Executing: /tmp/tmp.QFh2HHGgPh/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
9D0A7D764367AC46
gpg: requesting key 4367AC46 from hkp server keyserver.ubuntu.com
gpgkeys: key 9D0A7D764367AC46 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: keyserver receive failed: bad public key`

**Comment by sangoku116** [comment]
@pastak I typed: 

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9D0A7D764367AC46`

**Comment by siriusrh** [comment]
i am having that exact same issue on Ubuntu 16.04.5 LTS. Running "sudo apt-get update" results in:

W: GPG error: https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
W: The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pastak** [comment]
I get how to fix this problem https://blog.packagecloud.io/eng/2018/10/17/gpg-key-migration/#repository-users-how-can-i-fix-the-gpg-errors-from-a-packagecloudio-repository

- For APT(Debian / Ubuntu)
  - `curl -L https://packagecloud.io/user/repository/gpgkey | apt-key add -`
- For YUM(centos)
  - Please read blog article

**Comment by siriusrh** [comment]
Confirmed!

`$ curl -L https://packagecloud.io/gyazo/Gyazo-for-Linux/gpgkey | sudo apt-key add -`

did the trick for me. Thanks!
