### ISSUE TITLE
Unable to install on Linux Mint

### ISSUE THREAD

**Issue by OnkelTem** [gyazo/Gyazo-for-Linux#131]
Инструкции как я понимаю для убунты, но в README ни слова об этом. 

```
$ curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as LinuxMint/tessa.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

$ sudo apt-get install gyazo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gyazo

$ apt-cache search gyazo
$
```

Нельзя было просто дать ссылку на `.deb` или статический бинарник?

**Comment by pastak** [comment]
You should try on it https://github.com/gyazo/Gyazo-for-Linux/issues/35#issuecomment-138102251

**Comment by OnkelTem** [comment]
Дали ссылку на топик трехлетней давности. И чтт дальше?

**Comment by pastak** [comment]
try `% curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash` 🙏

**Comment by squarerobin** [comment]
For LinuxMint Tina: 
curl -s https://gist.github.com/squarerobin/6e7e9828460048b0962e5ebbe6a0ffa0/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gyazo-tina.deb.sh | sudo bash
