### ISSUE TITLE
Screen capture selector area showing up in screenshot

### ISSUE THREAD

**Issue by SaulSilver** [gyazo/Gyazo-for-Linux#132]
Thank you all for the great work making Gyazo! I use it normally on MacOS and it works like a charm :100: 

Tried to install it on Linux (Ubuntu 16.04) and whenever I screen capture, the selection area appears in the screenshot like in the following screenshot.

[![Image from Gyazo](https://i.gyazo.com/808d9bf229fa7d0fa8c828e8f31fcce8.png)](https://gyazo.com/808d9bf229fa7d0fa8c828e8f31fcce8)

Please let me know if you need more info about my system specs or anything else, thanks!

**Comment by pastak** [comment]
@SaulSilver Thanks for your using Gyazo 😄 

Try to change capturing command to `gnome-screenshot`. We write it on README https://github.com/gyazo/Gyazo-for-Linux#change-your-screenshot-commandtool

Please tell me more if it won't work.

**Comment by SaulSilver** [comment]
Oh sorry about opening an issue for this. I close it, thank you for your response!
