### ISSUE TITLE
I can't see my browser on Catalina, new mac OS

### ISSUE THREAD

**Issue by bapex** [gyazo/Gyazo-for-Linux#138]
I updated my mac os to Catalina today.
After that I found gyazo can capture only background on Catalina.
Do you have any solutions?

https://gyazo.com/44bb9c28ed94413045e0e0fc5d659820

**Comment by pastak** [comment]
Thanks for using Gyazo. We know this problem and try it to fix https://twitter.com/gyazo/status/1182169533382983680

(This repo is only for Gyazo-for-Linux so please send question via https://gyazo.com/contact or @gyazo on twitter at next time. )

**Comment by bapex** [comment]
Thank you for your reply.
I tried it and working finally!!
I'm sorry about the place I ask. Next time, I'll take care of about it.
Thanks!!

Toshi

2019年10月23日(水) 19:56 pastak <notifications@github.com>:
