### ISSUE TITLE
tricia does not have a Release file.

### ISSUE THREAD

**Issue by spfellers** [gyazo/Gyazo-for-Linux#145]
After running
```sh
curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
```
```sh
sudo apt-get install gyazo
```
I get
> The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/linuxmint tricia Release' does not have a Release file.

OS Version:
```sh
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.3 (Tricia)"

```

**Comment by AnatoleLucet** [comment]
Does the same on `Ubuntu 20.04 focal`

**Comment by pastak** [comment]
We will release soon 👍 

It is work arround for you https://github.com/gyazo/Gyazo-for-Linux/issues/131 (Any distro and version use same package file 😄)
