### ISSUE TITLE
Capture only black space on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by fliak** [gyazo/Gyazo-for-Linux#15]
Linux version 3.13.0-24-generic (buildd@batsu) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014

Distributor ID:	LinuxMint
Description:	Linux Mint 17 Qiana
Release:	17
Codename:	qiana

X: Mate

**Comment by drobune** [comment]
please try to this way.

 https://github.com/gyazo/Gyazo-for-Linux#how-to-change-screenshot-tool
