### ISSUE TITLE
Ubuntu 20.04 Failure to install

### ISSUE THREAD

**Issue by DHolmanCoding** [gyazo/Gyazo-for-Linux#150]
Running into an error when following the commands suggested in the README

Command 1: 
% curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as Ubuntu/focal.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

Command 2:
% sudo apt-get install gyazo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gyazo

**Comment by pastak** [comment]
We have released package for [ubuntu/focal](https://packagecloud.io/gyazo/gyazo-for-linux/packages/ubuntu/focal/gyazo_1.3.1_all.deb). How about `sudo apt-get install gyazo=1.3.1` ?

**Comment by DHolmanCoding** [comment]
Unfortunately, that does not seem to yield a different outcome:

% sudo apt-get install gyazo=1.3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gyazo

Is it possible that the curl command is suppressing messages indicating errors with the gyazo installation script?

**Comment by insaurabh** [comment]
I am facing the same issue. @DHolmanCoding did you find any workaround?

**Comment by loudar** [comment]
Also not working for me! Both with undefined and defined version, after running the script. Running Zorin OS 16, also overrode the os and dist variable

**Comment by interstate420productions** [comment]
Having Same issue.Gyazo not found.. something wrong with the Repo?

**Comment by Yuni321** [comment]
Same issues as what I was having.

Command 1:
Detected operating system as Ubuntu/noble.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.7.14
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/gyazo_gyazo-for-linux-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.

Command 2:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gyazo

And this is on Ubuntu 24.04 LTS

**Comment by interstate420productions** [comment]
Thank You works now :)

PopOS 22.04

**Comment by mchilson** [comment]
Not working for me on 24.04 LTS either...

**Setting up the repo**
Detected operating system as Ubuntu/noble.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.7.14
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/gyazo_gyazo-for-linux-archive-keyring.gpg
done.
Running apt-get update... done.
The repository is setup! You can now install packages.

**Trying to install the software**
mike@mike-ws:~/Desktop$ sudo apt-get install gyazo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gyazo
mike@mike-ws:~/Desktop$ sudo apt-get install gyazo=1.3.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gyazo

Any progress on this issue?

**Comment by hata6502** [comment]
You can use [gyazemon](https://github.com/hata6502/gyazemon) instead. 
(This is an unofficial Gyazo app.)
