### ISSUE TITLE
Script file location?

### ISSUE THREAD

**Issue by tonypartridge** [gyazo/Gyazo-for-Linux#151]
Hi Guys,

Where is the script.deb.sh file located for a PR? 

I want to add:

```
  if [ "$os" = "Zorin" ]; then
	os="Ubuntu";
  fi
```

after 
```

      else
        dist=`cut --delimiter='.' -f1 /etc/debian_version`
      fi

    else
      unknown_os
    fi
  fi

```

As a condition is all nice simple mapping :-)

**Comment by John-Smithys** [comment]
download the file at: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh
goto file location cd filepath
and run: sudo os=ubuntu dist=trusty ./script.deb.sh
then: sudo apt-get install gyazo

**Comment by pastak** [comment]
@tonypartridge Thanks for your issue but script.deb.sh is provided by packagecloud.io. You can detect os and version via an environment variable, this is an example: `os=ubuntu dist=\`cut --delimiter='.' -f1 /etc/debian_version\` curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash`

**Comment by tonypartridge** [comment]
You sure can, but for newer users would it not make more sense to pre-set them where possible? or detect the underlying OS opposed to OS Variable

**Comment by pastak** [comment]
Pull Request to wrap install script adding this behavior are welcome 👍
