### ISSUE TITLE
`apt update` fails with HTTP code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by purandarbarman** [gyazo/Gyazo-for-Linux#152]
Similar issue faced https://github.com/gyazo/Gyazo-for-Linux/issues/108.
Please increase the bandwidth https://packagecloud.io/arkane-systems/wsl-translinux/ubuntu/dists/bionic/InRelease
@pastak can you have a look

**Comment by pastak** [comment]
@purandarbarman Thanks for your notice but we have usable bandwidth for this period. Would you try once more?

**Comment by BigDaddyJ1569** [comment]
@pastak Hello, I've been having this issue as well. I've also read through the following threads
https://github.com/gyazo/Gyazo-for-Linux/issues/77
https://github.com/gyazo/Gyazo-for-Linux/issues/108

**Comment by pastak** [comment]
gmmm, we have usable bandwidth...

![image](https://user-images.githubusercontent.com/191533/96992924-8c9e5900-1565-11eb-9df0-cbc5a5c6a3e9.png)

**Comment by BigDaddyJ1569** [comment]
I'm not necessarily saying it's a bandwidth issue, but I"ve been encountering Error 429. I've also unsuccessfully tried forcing it as an unauthenticated repo

**Comment by GotthardG** [comment]
Hi, same issue today.
<img width="976" alt="Capture d’écran 2021-01-06 à 10 56 00" src="https://user-images.githubusercontent.com/51994228/103755234-c8e24100-500d-11eb-9ddc-008b88695305.png">
