### ISSUE TITLE
Linux Mint Cinammon 20 issues

### ISSUE THREAD

**Issue by dylansloann** [gyazo/Gyazo-for-Linux#155]
I have tried installing gyazo, but he initial error I received was about eh os detection, then I proceeded to try this command

curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash

which seemed to work, but I still came up with the error

"unable to locate package gyazo"

any help would be greatly appreciated as I loved gyazo on windows

**Comment by pastak** [comment]
It seems [Linux Mint 20 is not supported by packagecloud](https://packagecloud.io/docs#anchor-linuxmint).

Please try `os= linuxmint dist=tricia curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash`

**Comment by dylansloann** [comment]
@pastak the command did not work sadly, provides me with error message that your operating system is not supported by packagecloud.io.

**Comment by dylansloann** [comment]
it seems the

**Comment by dylansloann** [comment]
I did not mean to close this issue. But I do not think it will work until they release a linux mint 20 support.

**Comment by pastak** [comment]
They have support for Mint 20 yet
