### ISSUE TITLE
How do you capture gif?

### ISSUE THREAD

**Issue by halleycarleton** [gyazo/Gyazo-for-Linux#17]
On windows capturing gif is pretty straight forward, you just right-click gyazo in the tray and choose "Capture Gif" or use `ctrl+shift+g`. But I cannot figure out how to do the same on linux. When I right-click gyazo in the launcher the only option I get is "Gyazo", which is the same as just clicking the icon.

Could someone help me out?
Also are there any docs for this?

Ubuntu 14.04

**Comment by uiureo** [comment]
We're sorry that gif feature is not supported on Linux for now.

**Comment by guilhermesgb** [comment]
This software seems to be amazing. I just wish that you'd disclose that gif capturing doesn't work on Linux on your home page so we don't waste time trying until (if) we find out about it here.

**Comment by Alkaris** [comment]
GIF imaging support could be done with Byzanz - https://github.com/GNOME/byzanz

**Comment by uiureo** [comment]
Thanks @Alkaris. byzanz looks good. Does it work well for you?

**Comment by uiureo** [comment]
Unfortunately, linux support is not our priority. Let us know if there's a good alternative. We would be happy to add a link to it.

**Comment by guilhermesgb** [comment]
Oh, nice to know about other options! I ended up finding out about a command line tool (ffcast) which also does the job pretty well so maybe you could point to that link too? (Or even better, maybe integrate it into Gyazo!)

http://unix.stackexchange.com/questions/113695/gif-screencasting-the-unix-way

Cheers.

**Comment by Alkaris** [comment]
@uiureo Byzanz works really well, it even comes with it own little GIF playback tool to see what you recorded with Byzanz. You could probably implement a little GUI so you can select a region where you want to capture since Byzanz works from Terminal and you have to specify the **WIDTH** x **HEIGHT** and the **X** & **Y** position of the screen of where you want to record, and the duration of the GIF and whether if you want to record audio and capture the mouse cursor.

![byzanz-test](https://cloud.githubusercontent.com/assets/6682988/10515135/ab1a68d4-739d-11e5-8bfe-7208a3b6f8ba.gif)

**Comment by uiureo** [comment]
sounds good.

**Comment by thomas15v** [comment]
It looks fairly simple to add gif support to.

All you need is a mp4 recorder (Byzanz for example) for linux. And post the mp4 video to ´gif.gyazo.com´
with the following form information:
- id: possibly your userid
- width
- height
- scale: (seems to be 1 every time)
- metadata: {'title': 'test', 'app': 'chrome'}
- data: your file
Blank line followed with the the mp4 files content.

**Comment by Alkaris** [comment]
@thomas15v You can also create GIF's by using ffmpeg. I created an experimental kind of script which takes input video source file and makes output file to GIF, slightly more complicated than Byzanz, but works just as well. but file output size can vary depending how long and big of the GIF you are making.


```
#!/bin/sh

# Here'sa quick little ffmpeg video to GIF converter
# its all so simple, and all you need to do is change
# the format settings if desired for different outputs.

# actually before I can let you get started I just want
# point out what the current options I have chosen are
# just for this little script of mine.

## -t duration (input/output)
## -ss position (input/output) seeks out time where to start at
## -y (global) overwrite output files without asking
## -vf filtergraph (output) create filtergraph specified by filtergrtaph and filter the stream
## -v loglevel
## -gifflags
## +transdiff (transparency support) / -transdiff (non-transparency support)

#
# ok so now that is out the way here is the rest of the script
#


start_time=00:05				# start time of GIF
duration=7					# duration of GIF
palette="/tmp/palette.png"			# temporary palette
filters="fps=20,scale=440:-1:flags=lanczos"	# FPS and Scale of GIF

ffmpeg -v warning -ss $start_time -t $duration -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -ss $start_time -t $duration  -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2


# you should be able to use the script like so;
#
## $ ./makegif.sh video.mp4 anime.gif
#
# All credits to helping to make this script go to http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
# additional info for ffmpeg usage at https://www.ffmpeg.org/ffmpeg.html
```

Not the best of scripts, but you can achieve different quality of the GIF's you're making by changing the filter flags, the desired FPS and the scale.

**Comment by thomas15v** [comment]
@Alkaris the fun part is that Gyazo makes the gif itself. All we need is a command that can do the following:
1. Spawn in a selection window to select the area you wanna record
2. Has a pause/stop button during the recording
3. Creates a mp4 file

Than we only have to expand the ruby file with a "gif-command" section. And bam we have Gayzo gifs for linux 😄.

**Comment by pciavald** [comment]
any news on this ? just discovered this tool and I would love to be able to make gifs with it

**Comment by Alkaris** [comment]
@pciavald - Gyazo for Linux hasn't been updated in a long time, you'd be best seeking alternatives for now like using FFMPEG as I've provided in the script above or using Byzanz to make GIF's.

**Comment by mpsijm** [comment]
I've written a script that allows the user to select a rectangle, then uses Byzanz to record a GIF, and uploads it to Gyazo. Dropping it here if anyone wants to use it :slightly_smiling_face: 

https://github.com/mpsijm/gyazo-gif-for-linux
