### ISSUE TITLE
'E: Unable to locate package gyazo'

### ISSUE THREAD

**Issue by GNUzziHub** [gyazo/Gyazo-for-Linux#171]
Trying to install on the latest version of Ubuntu, normal install and sudo bash and updating give me the same error. The repo doesn't want to install no matter what.

Please help.

**Comment by pastak** [comment]
We recognize that the automatic release pipeline has stopped. We resume it so we believe it solves within 24 hours.

**Comment by pastak** [comment]
@GNUzziHub  hi, we update package for latest ubuntu. pls retry to install it. Thank you
