### ISSUE TITLE
Unable to install on Steam Deck (SteamOS 3.0)

### ISSUE THREAD

**Issue by robc9694** [gyazo/Gyazo-for-Linux#172]
When trying to install via Konsole I get the following message
Detected operating system as SteamOS/Holo.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
main: line 110: apt-get: command not found
Detected apt version as 
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...main: line 154: /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list: No such file or directory

Unable to run: 
    curl https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=SteamOS&dist=Holo&source=script

**Comment by pastak** [comment]
@robc9694 packagecloud, host the gyazo packages have no support for SteamOS. I have heard SteamOS Holo is based on Arch Linux so please retry with using yum and [overwrite os info like here](https://github.com/gyazo/Gyazo-for-Linux?tab=readme-ov-file#failed-to-install)
