### ISSUE TITLE
unsable to install 

### ISSUE THREAD

**Issue by KalyaAyaFlow** [gyazo/Gyazo-for-Linux#173]
getting this error when I  try 

kayla@kayla-System-Product-Name:~$ sudo apt-get install gyazo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gyazo

and this one when I try  update 
kayla@kayla-System-Product-Name:~$ sudo apt-get update
Hit:1 https://repo.steampowered.com/steam stable InRelease
Ign:2 http://packages.linuxmint.com virginia InRelease                         
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease                         
Hit:5 http://packages.linuxmint.com virginia Release                           
Hit:6 https://linux.teamviewer.com/deb stable InRelease                        
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                 
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease              
Hit:11 https://ppa.launchpadcontent.net/mixxx/mixxx/ubuntu jammy InRelease     
Get:9 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease [24.8 kB]
Err:9 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
Reading package lists... Done
W: GPG error: https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46
E: The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pastak** [comment]
@KalyaAyaFlow  hi, we update package. pls retry to install it. Thank you
