### ISSUE TITLE
Failed to download repository information

### ISSUE THREAD

**Issue by KalyaAyaFlow** [gyazo/Gyazo-for-Linux#174]
W:GPG error: https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D0A7D764367AC46, E:The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease' is not signed

**Comment by pastak** [comment]
We recognize that the automatic release pipeline has stopped. We resume it so we believe it solves within 24 hours.
