### ISSUE TITLE
linuxmint LMDE 6 "Faye"でのインストール方法

### ISSUE THREAD

**Issue by yuzu369** [gyazo/Gyazo-for-Linux#178]
OSの種類がlinuxmint LMDE 6 "Faye"です。
Debianベースです。
Gyazoのインストール方法を教えてください。

**Comment by pastak** [comment]
Readmeに書いてあるのaptの方法を参照してください https://github.com/gyazo/Gyazo-for-Linux?tab=readme-ov-file#failed-to-install

**Comment by yuzu369** [comment]
ご連絡ありがとうございます
Readmeを参照させていただきます
