### ISSUE TITLE
Annoying black border surrounding the images

### ISSUE THREAD

**Issue by arnoldstoba** [gyazo/Gyazo-for-Linux#36]
https://i.gyazo.com/de046ebf02e23460d07a451212e76a02.png

Is there a specific reason for the black border surrounding the captured images?
Annoying when taking screenshots that end up being on a white background.

**Comment by drobune** [comment]
It's seems difficult..
When I was using "scrot", screenshot-tool, i saw the same. 
Now I'm using "gnome-screenshot". it works good!

this is how to change screenshot

**Comment by arnoldstoba** [comment]
Alright ill try that. In general i'd suggest trying to avoid this problem in some kind since it is kind of "broken" by default. Even though its not such a big problem it can be pretty annoying at times.
Thanks for the quick answer. :+1:

**Comment by drobune** [comment]
:raised_hands:
