### ISSUE TITLE
Gyazo Update

### ISSUE THREAD

**Issue by DarkminecrafterHD** [gyazo/Gyazo-for-Linux#37]
An update from 1.1 to the new version 3 should be developed and released

**Comment by uiureo** [comment]
I don't understand. What kind of feature do you want?

**Comment by DarkminecrafterHD** [comment]
For example the giff capture function.
or the copy of the gyazo's links once it've been uploaded.
those kind of things that has been implemented in the windows version.

Also, taking in acount that we're on linux.. a --help parameter and other ones wouldn't hurt anyone. but thas is only a suggestion.

Sorry about my English.

**Comment by uiureo** [comment]
We're sorry that Linux support is not so good as Windows or OSX.
That is not our priority for now. But some of our developers use the Linux version, so some updates will come.

> Also, taking in acount that we're on linux.. a --help parameter and other ones wouldn't hurt anyone. but thas is only a suggestion.

This is a good idea.

Thanks @DarkminecrafterHD for the feedback.

**Comment by DarkminecrafterHD** [comment]
Ok thanks for your time.
Hope that one day Both versions could be equal at features and developement.
