### ISSUE TITLE
put CircleCI status badge on README

### ISSUE THREAD

**Issue by imkitchen** [gyazo/Gyazo-for-Linux#39]
Hi, there!

Could you show us build status?
It requires CircleCI API token to get badge image.

best regards :smiley: 

FYI: http://blog.a-know.me/entry/2015/01/04/123432

**Comment by uiureo** [comment]
Done. It seems the token was not required.

Thanks @imkitchen for suggestion.

**Comment by imkitchen** [comment]
thanks a lot @uiureo san!
