### ISSUE TITLE
Installing on Fedora 21

### ISSUE THREAD

**Issue by JPGlaser** [gyazo/Gyazo-for-Linux#41]
Hello All,

I'm having some issues installing the rpm onto Fedora 21. Following the instructions, the repo is set up correctly and listed on yum repolist. However, I cannot seem to install the gyazo package as it reports that none exist. Any ideas on how this could happen?

~ Joe G.

**Comment by pastak** [comment]
@JPGlaser Sorry, we released for Fedora today. So please retry it.
