### ISSUE TITLE
Doesn't work on Ubuntu 12.04

### ISSUE THREAD

**Issue by OnkelTem** [gyazo/Gyazo-for-Linux#5]
Hi.

It doesn't work on Ubuntu 12.04/Gnome 3.
When I run gazo executable, cursor changes to cross-hair, but after this I can't select area on the screen: when I drag mouse selection rectangle area doesn't appear correctly like it is being breaking by something. Then after releasing left mouse button, gyazo website is opened and shows random image: random area, from random monitor, from random workspace. For example, when I was selecting an area on second monitor on first workspace, resulting screenshot was made from 3rd monitor of 4th workspace.

**Comment by onetime-account** [comment]
Still have this problem on ubuntu 14.04/Gnome3
