### ISSUE TITLE
Gyazo won't capture what I want

### ISSUE THREAD

**Issue by K4lim** [gyazo/Gyazo-for-Linux#53]
Hey,

I installed Gyazo the way it was described here, but when I want to take a screenshot of my desktop for example, I only get a black background.
(https://gyazo.com/61f9c7c18e3eeb4f2532408609707b99)

On top of that i can't do screenshots of my browser. (https://gyazo.com/fda111919b5d1fe97f0b1a5c89994776  I tried to make a screen of the Gyazo-GitHub page)

I'm quite new to Linux by the way.

OS: Linux-Mint 17.3
Kernel Version: 3.19
Graphics card: MSI 970GTX

I hope someone can help me. If you need more information just tell me.

**Comment by TheDarocker** [comment]
Reproducible on Ubuntu. Your best option is using a combination of the Gyazo web-extension on Chrome (and maybe Firefox) with the desktop app as they don't update this much anymore- or at least that I've seen.

**Comment by pastak** [comment]
Hello. I think this blackout is caused by ffmpeg. So please try to use gnome-screenshot https://github.com/gyazo/Gyazo-for-Linux#how-to-change-screenshot-tool
