### ISSUE TITLE
Gyazo for Linux not lauching on CentOS 6

### ISSUE THREAD

**Issue by ethancedrik** [gyazo/Gyazo-for-Linux#61]
I am currently running an up to date version of CentOS 6.7, and I have installed Gyazo and ImageMagick is also installed, however whenever I try and click the "Gyazo" icon it doesn't open at all, and also upon running "gyazo" in the terminal I get this

[Ethan@localhost ~]$ gyazo
/usr/bin/gyazo:65: odd number list for Hash
  app: active_window_name,
      ^
/usr/bin/gyazo:65: syntax error, unexpected ':', expecting '}'
  app: active_window_name,
      ^
/usr/bin/gyazo:66: syntax error, unexpected ':', expecting '='
  title: active_window_name,
        ^
/usr/bin/gyazo:67: syntax error, unexpected ':', expecting '='
  url: xuri,
      ^
/usr/bin/gyazo:68: syntax error, unexpected ':', expecting '='
  note: "#{active_window_name}\n#{xuri}"
       ^
/usr/bin/gyazo:69: syntax error, unexpected '}', expecting $end

**Comment by ethancedrik** [comment]
If there is anything else I need to install or can configure to get this working please let me know :)

**Comment by drobune** [comment]
Thank you for report!
It seems that you use old ruby version, under 1.8.7.
Could you check your ruby version?
