### ISSUE TITLE
Gyazo for Linux not installing on Xubuntu 16.04

### ISSUE THREAD

**Issue by MJae** [gyazo/Gyazo-for-Linux#65]
I've installed Gyazo for Linux before and I didn't encounter any issues. However, I've tried several times but I've not succeeded installing it on this other machine. It never resolves. Then again, it's running a different OS. The previous one was running on Xubuntu 14.04. Is it because of the OS difference or is the issue something else?

**Comment by drobune** [comment]
Thanks for your report.

I think there is no issue at deb-package. 
Could you show your logs?

**Comment by pastak** [comment]
@MJae hi! 

I think this issue's reason is that Xubuntu is specified as `xubuntu` not `ubuntu`. So would you try to https://github.com/gyazo/Gyazo-for-Linux/issues/35

**Comment by fantasticallyurs** [comment]
Yeah, this is still an issue, could ya fix it?

**Comment by pastak** [comment]
This issue depends on packagecloud API. We cannot solve it.

**Comment by fantasticallyurs** [comment]
oh damn, could you suggest a similar app for screenshots on ubuntu 16.04 (64 bit)? 
Thanks for the quick reply!

**Comment by Gloomshroud** [comment]
While not as good, nor as cloud-oriented, the apps Shutter and Gnome Screenshot Tool are widely available. Not as ideal as Gyazo, but they are quick alternatives until the API is ammended.

**Comment by ext0** [comment]
I had a similar issue, and fixed it by just installing the raw .deb file from packagecloud.

I put together the following command to get it working on my Ubuntu MATE 16.10 system (hopefully it'll work for yours too).

`curl -O -J -L https://packagecloud.io/gyazo/gyazo-for-linux/packages/ubuntu/breezy/gyazo_1.2_all.deb/download &> /dev/null & dpkg -i gyazo_1.2_all.deb & sudo apt-get install -f`

**Comment by renjithis** [comment]
The apt installation command is missing an &&
`curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash **_&&_** sudo apt-get install gyazo`

**Comment by mbarona** [comment]
thanks @renjithis i was able to successfully install it on ubuntu 16.04 LTS
