### ISSUE TITLE
Gyazo screenshots what's behind the active window

### ISSUE THREAD

**Issue by vsod99** [gyazo/Gyazo-for-Linux#66]
Often, I'll go to screenshot, let's say, a chromium page, but instead, it screenshots the discord application I have open in the background. Minimizing everything in the background does not help either.

**Comment by pastak** [comment]
@vsod99 If you use Ubuntu please set to use `gnome-screenshot`.

https://github.com/gyazo/Gyazo-for-Linux#change-your-screenshot-commandtool
