### ISSUE TITLE
Signature uses weak digest algorithm (SHA1) (apt/deb)

### ISSUE THREAD

**Issue by missingcharacter** [gyazo/Gyazo-for-Linux#69]
Hi,

I didn't see any other issue reporting this:
` https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu/dists/xenial/InRelease: Signature by key F86AA916A2195E121AEDB11437BBEE3F7AD95B3F uses weak digest algorithm (SHA1)`

This happens when trying to update the repo ( `apt update`), the problem and solution are similar to this: https://github.com/github/git-lfs/issues/1110

**Comment by drobune** [comment]
Thank you for report.
I have confirm that this warning is fixed by reindex repo.
So I'll upgrade version of this app.
