### ISSUE TITLE
Unable to download repo config

### ISSUE THREAD

**Issue by mvducatti** [gyazo/Gyazo-for-Linux#77]
I'm getting this error and I don't know what to do

Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=elementary&dist=loki&source=script

Please, can you help me?

Currently using Elementary OS / Loki

**Comment by pastak** [comment]
Elementary OS Loki is based on Ubuntu 16.04 LTS.  So please try this command to install `curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash && sudo apt-get install gyazo`

**Comment by mvducatti** [comment]
Hello! I followed your direction and got this error

/* curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash && sudo apt-get install gyazo
Detected operating system as elementary/loki.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...curl: (22) The requested URL returned error: 404 Not Found


Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=elementary&dist=loki&source=script

This usually happens if your operating system is not supported by
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this. */

Could you help me please? I really want Gyazo :(

Thanks in advance!

Best Regards,

mvducatti.

On Dom, Dez 11, 2016 at 12:02 , pastak <notifications@github.com> wrote:

Elementary OS Loki is based on Ubuntu 16.04 LTS. So please try this command to install curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash && sudo apt-get install gyazo

**Comment by pastak** [comment]
Oh, thanks for your more information.

I'm sorry telling you wrong 🙇 

It is correct script I tweaked to run alternative ubuntu/debian `% curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash`

Please try it.

**Comment by pchard** [comment]
Err:10 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu trusty InRelease   
  429  Too Many Requests [IP: 50.97.198.58 443]
Reading package lists... Done                    
E: Failed to fetch https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu/dists/trusty/InRelease  429  Too Many Requests [IP: 50.97.198.58 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by pastak** [comment]
@pchard Thanks for notice. We will update packagecloud for a while. https://github.com/gyazo/Gyazo-for-Linux/issues/108#issuecomment-348839861
