### ISSUE TITLE
Gyazo captured image is black or nearly all black

### ISSUE THREAD

**Issue by benfoden** [gyazo/Gyazo-for-Linux#78]
Here is a video a user created: https://www.youtube.com/watch?v=3Z911UKtGz0

They can capture the screen but the uploaded image is all black.

I am still waiting to hear back about which distribution of linux they are using and I will update.

Edit:  Ubuntu 14.04 64 bit, GTX 670 w/ 375.26, full hw info: http://paste.ee/p/AMK6t

**Comment by pastak** [comment]
Gyazo Linux uses `import` command to capture display on Ubuntu as default and it sometimes captures broken.

You can avoid this problem to use `gnome-screenshot` command instead of `import`. https://github.com/gyazo/Gyazo-for-Linux#change-your-screenshot-commandtool

**Comment by koiri2** [comment]
good job
