### ISSUE TITLE
Can't edit or delete uploaded screenshot

### ISSUE THREAD

**Issue by branchard** [gyazo/Gyazo-for-Linux#83]
It's not possible to edit or delete the uploaded screenshot as the Windows or browser-extension version of Gyazo: 
![peek 09-04-2017 04-21](https://cloud.githubusercontent.com/assets/6990948/24834108/229e44dc-1cdc-11e7-9f87-6ee82e464961.gif)

I think it's because Gyazo-for-Linux uses the old CGI Gyazo API ([https://github.com/gyazo/Gyazo-for-Linux/blob/master/src/gyazo.rb#L20](https://github.com/gyazo/Gyazo-for-Linux/blob/master/src/gyazo.rb#L20)).
Can I update Gyazo-for-Linux to the [new API](https://gyazo.com/api/docs) ?

**Comment by pastak** [comment]
Thanks for report. We'll check it.
