### ISSUE TITLE
Ubuntu 16.04 LTS: Screenshots have lines 

### ISSUE THREAD

**Issue by tanmaykumar** [gyazo/Gyazo-for-Linux#87]
The screen shots have lines on them. This happens consistently. Running version 1.2ubuntu1-wily1 on Ubuntu 16.04 LTS Unity.

[Example](https://gyazo.com/7e3441a0f2572fc66f21129fc5e9be43)

EDIT: Issue does not resolve by changing to gnome-screenshot, scrot or xfce4-screenshooter

**Comment by pastak** [comment]
You should use `gnome-scfeenshot`. It's problem of `convert`
