### ISSUE TITLE
Strange lines

### ISSUE THREAD

**Issue by espanalfc** [gyazo/Gyazo-for-Linux#88]
When taking a screenshot on ubuntu 17, it looks like this every time https://gyazo.com/9b6a2d82c61f5e66069c21539c77778f

**Comment by pastak** [comment]
@espanalfc duplicated https://github.com/gyazo/Gyazo-for-Linux/issues/87

please try to change screenshot command to gnome-screenshot https://github.com/gyazo/Gyazo-for-Linux#change-your-screenshot-commandtool

**Comment by anibyl** [comment]
@pastak great, it works!

Don't you think that `gnome-screenshot` should be chosen by default for some distros (like ubuntu)?

**Comment by pastak** [comment]
I think It's better. PRs are welcome.
