### ISSUE TITLE
I have Gyazo Pro but the gyazos I capture are not added to "My captures"

### ISSUE THREAD

**Issue by Cashews54** [gyazo/Gyazo-for-Linux#89]
I have a Gyazo pro account.  On Windows and Mac, if I take a Gyazo, it will show up under "My captures" [here](https://gyazo.com/captures) and there I can browse my entire history of Gyazo's I have captured.

However if I take a Gyazo on Linux, it is NOT added to "My captures."  The Gyazo URL will open in my browser where I am logged in to my Pro account, but if I go to "My captures" it will show up under my "Browsing history" but not my collection.  

How do I link my account?  Thanks!

**Comment by Cashews54** [comment]
Anybody know about Pro account integration?

**Comment by hiroshi** [comment]
Hi,

I create a pull, https://github.com/gyazo/Gyazo-for-Linux/pull/109, to patch this issue.

Check to see it works if you please.

This line replace the gyazo script with patched version.
```
curl https://raw.githubusercontent.com/gyazo/Gyazo-for-Linux/13c9559d88a382fffdec86bec7371ed0a242ae44/src/gyazo.rb > /usr/bin/gyazo
```

**Comment by Cashews54** [comment]
@hiroshi I didn't build from source so your command didn't work for me.  (`/usr/src/gyazo` is not a folder I have.)

But if your pull request gets approved, I can test it.

**Comment by Cashews54** [comment]
@hiroshi Looks like your PR fixed the issue, my gyazos now show up under my account!  Thank you!!

**Comment by hiroshi** [comment]
@Cashews54 
That's sound good! Thank you for telling us.
BTW We release this change as version 1.3.1.
