### ISSUE TITLE
Unable to locate package gyazo

### ISSUE THREAD

**Issue by ViniciusBorges22** [gyazo/Gyazo-for-Linux#90]
Although there's no error while running `curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash`:

> Detected operating system as LinuxMint/sonya.
> Checking for curl...
> Detected curl...
> Running apt-get update... done.
> Installing apt-transport-https... done.
> Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
> Importing packagecloud gpg key... done.
> Running apt-get update... done.
> 
> The repository is setup! You can now install packages.

After `sudo apt-get install gyazo` I get this error on the last line: 

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package gyazo

**Comment by prezine** [comment]
I have the same Problem, how do we fix this?

**Comment by mhimranhossain97** [comment]
try `curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash`

then `sudo apt-get install gyazo=1.3.1`

hope it will get installed..
