### ISSUE TITLE
Release' does not have a Release file.

### ISSUE THREAD

**Issue by Joaobranquinho** [gyazo/Gyazo-for-Linux#91]
I have linux mint sonya. 
When I `apt-get update` the following error appears:

`W: The repository 'https://packagecloud.io/gyazo/gyazo-for-linux/linuxmint sonya Release' does not have a Release file.`

I'm not even able to install it.

**Comment by Joaobranquinho** [comment]
@pastak

**Comment by pastak** [comment]
@Joaobranquinho Thanks for notice. I have released for `linuxmint/sonya` 😄
