### ISSUE TITLE
How to retrieve proper gyazo user ID? 

### ISSUE THREAD

**Issue by fukuchi** [gyazo/Gyazo-for-Linux#93]
Hi,

I want to connect the gyazo app to my existing gyazo account. As far as I know, I should put my gyazo ID in ~/.gyazo.id , but I don't know my gyazo ID.

How can I retrieve proper ID?

**Comment by carestad** [comment]
Just found out how.

1. Go to https://gyazo.com/settings, make sure you are logged in with your user account
2. View the source of the page (CTRL+U) and look around line 15. You will see a line that looks a little bit like this:

```
ga('set', 'userId', 'abcdefghijklmnopqrstuvwxyz0123456789');
```

Where the `abcde(...)` part is your ID.

**Comment by fukuchi** [comment]
Thank you, @carestad.

It did not work as expected, however. I could find my userId using the above method, but the ID in .gyazo.id replaced with newly given ID after launching gyazo.

One possible factor is that the userId of mine is "YYYYMMDD..." style 14 digits number, not MD5-like hash.

Probably they reject my user ID from gyazo client?
